spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: utf-8
    cache: false
  datasource:
    type:  com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/website_search?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    #spring boot集成mybatis的方式打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


